kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: sj-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: sj-analysis
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          gateUrl: https://isd-demo.argo-dev.opsmx.net/
          application: final-tests
          user: admin
          lifetimeHours: "0.1"
          threshold:
            pass: 80
            marginal: 60
          globalMetricTemplate: PrometheusTemplateTest
          globalLogTemplate: logtemp
          services:
          - logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"
            metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
            baselineMetricScope: "argocd,{{args.baseline-hash}},final-tests"
            canaryMetricScope: "argocd,{{args.canary-hash}},final-tests"
            metricTemplateName: "PrometheusMetricTemplate"
          - metricScopeVariables: "${namespace_key},${pod_key}"
            baselineMetricScope: "argocd,{{args.baseline-hash}}"
            canaryMetricScope: "argocd,{{args.canary-hash}}"
