kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: sj-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: sj-analysis
      count: 1
      initialDelay: 10s
      provider:
        opsmx:
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: final-tests
          user: admin
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          globalMetricTemplate: PrometheusMetricTemplate
          globalLogTemplate: qalogtemp
          services:
          - logTemplateName: logtemp
            logScopeVariables: "kubernetes.pod_name"
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"
            metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
            baselineMetricScope: "argocd,{{args.baseline-hash}},final-tests"
            canaryMetricScope: "argocd,{{args.canary-hash}},final-tests"
          - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
            baselineMetricScope: "argocd,{{args.baseline-hash}},issuegenapp-canary"
            canaryMetricScope: "argocd,{{args.canary-hash}},issuegenapp-canary"
