kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: oes-analysis-for-newrelic-custom
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: oes-analysis-for-newrelic-custom
      count: 1
      initialDelay: 30s
      provider:
        opsmx:
          gateUrl: https://isd-dev.argo-dev.opsmx.net/
          application: newreliccustomappl
          user: admin
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: "svc1"
            gateName: "gate1"
            metricTemplateName: newrelictemplate
            metricScopeVariables: "resource.labels.container_name"
            baselineMetricScope: "oes-platform-br"
            canaryMetricScope: "oes-platform-br"
          - serviceName: "svc2"
            gateName: "gate1"
            metricTemplateName: newrelictemplate
            metricScopeVariables: "resource.labels.container_name"
            baselineMetricScope: "oes-platform-br"
            canaryMetricScope: "oes-platform-br"
