apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: testapp
spec:
  metrics:
    - name: testapp
      provider:
        opsmx:
          gateUrl: https://argoqa.isd-dev.opsmx.net/
          user: admin
          application: testapplication17742
          baselineStartTime: "2022-08-20T13:15:00Z"
          lifetimeHours: "0.1"
          threshold: 
            pass: 80
            marginal: 60
          services:
          - logTemplateName: testLogTemplateName65707
            logScopeVariables: "kubernetes.container_name"
            baselineLogScope: ".*{{args.baseline-hash}}.*"
            canaryLogScope: ".*{{args.canary-hash}}.*"
            metricTemplateName: testmetrictemplate17742
            metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
            baselineMetricScope: "argocd,{{args.baseline-hash}},demoapp-issuegen"
            canaryMetricScope: "argocd,{{args.canary-hash}},demoapp-issuegen"
