kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: qa-analysis
spec:
  args:
    - name: canary-hash
    - name: baseline-hash
  metrics:
    - name: qa-analysis
      count: 1
      initialDelay: 30s
      provider:
        opsmx:
          gateUrl: https://argocd-isdargo.isd-dev.opsmx.net/
          application: datadoapplication
          user: admin
          lifetimeHours: "0.1"
          threshold:
            pass: 80
            marginal: 60
          services:
          - metricTemplateName: CUSTOMDatadog
            metricScopeVariables: "variable1"
            baselineMetricScope: "service:baseapp"
            canaryMetricScope: "service:canaryapp"
            
