kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: oes-analysis
spec:
  args:
    - name: experiment-hash
  metrics:
    - name: oes-analysis
      count: 1
      provider:
        opsmx:
          gateUrl: https://argoqa-helm.isd-dev.opsmx.net
          baselineStartTime: "2022-09-16T11:29:46.915Z"
          canaryStartTime: "2022-09-19T11:29:46.915Z"
          application: datadogbyqa
          user: admin
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: datadogservice
            metricTemplateName: datadogcustom
            metricScopeVariables: "variable1"
            baselineMetricScope: "service:baseapp"
            canaryMetricScope: "service:canaryapp"
