kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: oes-analysis
spec:
  args:
    - name: experiment-hash
  metrics:
    - name: oes-analysis
      count: 1
      provider:
        opsmx:
          gateUrl: https://argoqa-helm.isd-dev.opsmx.net
          application: demoapphash
          user: admin
          lifetimeHours: "0.05"
          threshold:
            pass: 80
            marginal: 60
          services:
          - serviceName: service2
            logTemplateName: newreliccustom
            logScopeVariables: "app_key,pod_key"
            baselineLogScope: "issugen-baseline,6944b5c7df"
            canaryLogScope: "issugen-baseline,76f78f85ff"
